In [3]:
from heti_stack.applicant import ApplicantPool, hospital_generator

test_pool = ApplicantPool([
    ("stack", 0.50),
    ("random", 0.50)
])

In [4]:
test_pool.candidate_df["preferences"]

0       [0, 4, 8, 9, 2, 7, 12, 5, 11, 3, 1, 6, 10, 13,...
1       [8, 0, 7, 14, 10, 5, 2, 3, 12, 6, 11, 1, 13, 9...
2       [0, 4, 8, 9, 2, 7, 12, 5, 11, 3, 1, 6, 10, 13,...
3       [13, 7, 3, 6, 2, 8, 4, 9, 1, 14, 10, 5, 0, 12,...
4       [0, 4, 8, 9, 2, 7, 12, 5, 11, 3, 1, 6, 10, 13,...
                              ...                        
1534    [9, 0, 12, 8, 7, 4, 11, 14, 10, 5, 2, 3, 13, 6...
1535    [1, 5, 2, 7, 8, 0, 6, 12, 14, 10, 4, 11, 9, 3,...
1536    [12, 8, 14, 5, 4, 13, 6, 1, 3, 0, 9, 11, 7, 10...
1537    [7, 12, 1, 8, 5, 9, 6, 0, 10, 13, 14, 2, 4, 3,...
1538    [10, 8, 3, 1, 2, 4, 7, 11, 5, 6, 13, 12, 14, 0...
Name: preferences, Length: 1539, dtype: object

In [5]:
import numpy as np
np.vstack(test_pool.candidate_df["preferences"])

array([[ 0,  4,  8, ..., 10, 13, 14],
       [ 8,  0,  7, ..., 13,  9,  4],
       [ 0,  4,  8, ..., 10, 13, 14],
       ...,
       [12,  8, 14, ...,  7, 10,  2],
       [ 7, 12,  1, ...,  4,  3, 11],
       [10,  8,  3, ..., 14,  0,  9]])

In [6]:
hospital_generator.dra_capacities

array([ 0, 13,  0, 18,  0,  0, 40,  0,  0,  0, 49, 69,  0, 32, 45])

In [7]:
np.array(hospital_generator.dra_capacities)

array([ 0, 13,  0, 18,  0,  0, 40,  0,  0,  0, 49, 69,  0, 32, 45])

In [8]:
np.array(list(hospital_generator.dra_capacities))

array([ 0, 13,  0, 18,  0,  0, 40,  0,  0,  0, 49, 69,  0, 32, 45])

In [9]:
dra_hospital_capacities = _
dra_hospitals = np.where(dra_hospital_capacities > 0)

In [10]:
dra_hospitals

(array([ 1,  3,  6, 10, 11, 13, 14], dtype=int64),)

In [11]:
pref_arr = np.vstack(test_pool.candidate_df["preferences"])
pref_arr

array([[ 0,  4,  8, ..., 10, 13, 14],
       [ 8,  0,  7, ..., 13,  9,  4],
       [ 0,  4,  8, ..., 10, 13, 14],
       ...,
       [12,  8, 14, ...,  7, 10,  2],
       [ 7, 12,  1, ...,  4,  3, 11],
       [10,  8,  3, ..., 14,  0,  9]])

In [12]:
pref_arr[:,dra_hospitals]

array([[[ 4,  9, 12, ...,  6, 13, 14]],

       [[ 0, 14,  2, ...,  1,  9,  4]],

       [[ 4,  9, 12, ...,  6, 13, 14]],

       ...,

       [[ 8,  5,  6, ..., 11, 10,  2]],

       [[12,  8,  6, ...,  2,  3, 11]],

       [[ 8,  1,  7, ..., 12,  0,  9]]])

In [13]:
dra_hospitals

(array([ 1,  3,  6, 10, 11, 13, 14], dtype=int64),)

In [14]:
dra_hospitals[0]

array([ 1,  3,  6, 10, 11, 13, 14], dtype=int64)

In [15]:
pref_arr[:,dra_hospitals[0]]

array([[ 4,  9, 12, ...,  6, 13, 14],
       [ 0, 14,  2, ...,  1,  9,  4],
       [ 4,  9, 12, ...,  6, 13, 14],
       ...,
       [ 8,  5,  6, ..., 11, 10,  2],
       [12,  8,  6, ...,  2,  3, 11],
       [ 8,  1,  7, ..., 12,  0,  9]])

In [16]:
dra_hospital_capacities

array([ 0, 13,  0, 18,  0,  0, 40,  0,  0,  0, 49, 69,  0, 32, 45])

In [17]:
np.where(dra_hospital_capacities > 0)

(array([ 1,  3,  6, 10, 11, 13, 14], dtype=int64),)

In [18]:
pref_arr[:,dra_hospitals[0]]

array([[ 4,  9, 12, ...,  6, 13, 14],
       [ 0, 14,  2, ...,  1,  9,  4],
       [ 4,  9, 12, ...,  6, 13, 14],
       ...,
       [ 8,  5,  6, ..., 11, 10,  2],
       [12,  8,  6, ...,  2,  3, 11],
       [ 8,  1,  7, ..., 12,  0,  9]])

In [19]:
pref_arr.shape

(1539, 15)

In [20]:
pref_arr[:,dra_hospitals[0]].shape

(1539, 7)

In [21]:
np.where(pref_arr == 0)

(array([   0,    1,    2, ..., 1536, 1537, 1538], dtype=int64),
 array([ 0,  1,  0, ...,  9,  7, 13], dtype=int64))

In [22]:
find_zeros = np.vectorize(lambda t: 1 if t == 0 else 0)

In [23]:
find_zeros(pref_arr)

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0]])

In [24]:
find_zeros = np.vectorize(lambda t: int(t == 0))

In [25]:
find_zeros(pref_arr)

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0]])

In [26]:
original_indices = np.where(dra_hospital_capacities > 0)[0]
alloc_arr = np.zeros_like(pref_arr)
alloc_arr[:, original_indices] = find_zeros(pref_arr[:, original_indices])
alloc_arr

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0]])

In [27]:
find_zeros(pref_arr[:, original_indices])

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0]])

In [28]:
alloc_arr[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
len(alloc_arr[0])

15

In [30]:
pref_arr[:, original_indices] == 0

array([[False, False, False, ..., False, False, False],
       [ True, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False,  True, False]])

In [31]:
pref_arr.dtype

dtype('int32')

In [32]:
dra_firsts = pref_arr[:, original_indices] == 0
dra_firsts.astype('int32')

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0]])

In [33]:
cdf = test_pool.candidate_df

In [34]:
cdf

uid strategy  \
0     383e3983-c235-47f5-891a-a4ac07a309b3    stack   
1     c2c60c8e-fc77-4089-a906-c3c975066c93   random   
2     cc1d0c67-414f-4ae9-8351-e685487c5f83    stack   
3     ba629b45-2fb7-4f20-8ad9-e842b5ec5131   random   
4     dbcdb2c9-8a62-4f2e-bac9-884a98c083e2    stack   
...                                    ...      ...   
1534  1961e953-3ef8-44e8-b97d-957cdce1c207   random   
1535  45329110-5fe3-4822-826a-3134fb414b3d   random   
1536  d2bf5362-fc44-47b7-8b6d-b4694492ab42   random   
1537  0d6ca501-5876-4987-ae36-c0ba8f21b88e   random   
1538  7a73eb47-27c0-4bd2-a353-bc92d8e94323   random   

                                            preferences  category allocation  \
0     [0, 4, 8, 9, 2, 7, 12, 5, 11, 3, 1, 6, 10, 13,...         0       None   
1     [8, 0, 7, 14, 10, 5, 2, 3, 12, 6, 11, 1, 13, 9...         0       None   
2     [0, 4, 8, 9, 2, 7, 12, 5, 11, 3, 1, 6, 10, 13,...         0       None   
3     [13, 7, 3, 6, 2, 8, 4, 9, 1, 14, 10, 5, 0, 12,...         0       None   
4     [0, 4, 8, 9, 2, 7, 12, 5, 11, 3, 1, 6, 10, 13,...         0       None   
...                                                 ...       ...        ...   
1534  [9, 0, 12, 8, 7, 4, 11, 14, 10, 5, 2, 3, 13, 6...         5       None   
1535  [1, 5, 2, 7, 8, 0, 6, 12, 14, 10, 4, 11, 9, 3,...         5       None   
1536  [12, 8, 14, 5, 4, 13, 6, 1, 3, 0, 9, 11, 7, 10...         5       None   
1537  [7, 12, 1, 8, 5, 9, 6, 0, 10, 13, 14, 2, 4, 3,...         5       None   
1538  [10, 8, 3, 1, 2, 4, 7, 11, 5, 6, 13, 12, 14, 0...         5       None   

     preference_number  is_dra  
0                 None   False  
1                 None   False  
2                 None   False  
3                 None   False  
4                 None   False  
...                ...     ...  
1534              None   False  
1535              None   False  
1536              None   False  
1537              None   False  
1538              None   False  

[1539 rows x 7 columns]

In [35]:
cdf.index

RangeIndex(start=0, stop=1539, step=1)

In [36]:
pref_arr[cdf.index]

array([[ 0,  4,  8, ..., 10, 13, 14],
       [ 8,  0,  7, ..., 13,  9,  4],
       [ 0,  4,  8, ..., 10, 13, 14],
       ...,
       [12,  8, 14, ...,  7, 10,  2],
       [ 7, 12,  1, ...,  4,  3, 11],
       [10,  8,  3, ..., 14,  0,  9]])

In [37]:
alloc_arr

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0]])

In [38]:
(alloc_arr == 0).all(axis=1)

array([ True, False,  True, ...,  True,  True, False])

In [39]:
alloc_arr[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [40]:
cdf.index

RangeIndex(start=0, stop=1539, step=1)

In [41]:
hdf = hospital_generator.hospital_df
hdf

name abbreviation  is_dra  \
0              Network 1: Inner West & Western Plains          RPA   False   
1                      Network 2: Bankers and Campers    Bankstown    True   
2   Network 3: Concord & Canterbury & Broken Hill ...      Concord   False   
3           Network 4: South West Sydney, Tweed Heads    Liverpool    True   
4                   Network 5: North Shore & Port Mac          RNS   False   
5               Network 6: Hornsby & Northern Beaches      Hornsby   False   
6                    Network 7: Central Coast Network      Gosford    True   
7   Network 8: St George, Sutherland, Albury & Gri...          StG   False   
8                      Network 9: From Coast to Coast          POW   False   
9             Network 10: Eastern to Greater Southern          StV   False   
10                                 Network 11: Oceans   Wollongong    True   
11                     Network 12: Hunter New England          JHH    True   
12                                Network 13: Westnet     Westmead   False   
13                Network 14: Nepean & Blue Mountains       Nepean    True   
14                           Network 15: Central West    Blacktown    True   

    dra  capacity  firsts  spots_remaining filled_spots    weight  
0     0        64      42               64           []  0.114754  
1    13        51       2               51           []  0.005464  
2     0        49      30               49           []  0.081967  
3    18        74      17               74           []  0.046448  
4     0        71      50               71           []  0.136612  
5     0        40      21               40           []  0.057377  
6    40        68      17               68           []  0.046448  
7     0        76      54               76           []  0.147541  
8     0        51      35               51           []  0.095628  
9     0        54      29               54           []  0.079235  
10   49        66       8               66           []  0.021858  
11   69       125      17              125           []  0.046448  
12    0       121      30              121           []  0.081967  
13   32        63      13               63           []  0.035519  
14   45        54       1               54           []  0.002732

In [42]:
pref_arr[:, 2]

array([ 8,  7,  8, ..., 14,  1,  3])

In [43]:
np.sum(pref_arr[:,2])

11838

In [44]:
from heti_stack.sim import CategoricalSimulation

test_cat_sim = CategoricalSimulation([
    ("stack", 0.50),
    ("random", 0.50)
])

In [45]:
test_cat_sim

In [46]:
test_cat_sim.run()

In [47]:
hdf["spots_remaining"][11]

125

In [49]:
cdf[cdf["category"] == 1]

uid strategy  \
916   f585b510-46ae-4166-9693-bc18c3b47597   random   
917   05bd8d36-dd05-4a6e-a6b2-2e5e18a7c846    stack   
918   8d239cb2-b52a-4136-8a14-d9511710bd27    stack   
919   c3d9fe70-4a2f-4bc8-9bd5-5dc1af583dd3   random   
920   0be77d32-fe59-4f77-8067-317b011ae256    stack   
...                                    ...      ...   
1113  1b4524de-38d3-440a-85fe-3e1538e590be    stack   
1114  f3febc8f-2400-4b58-844a-9420a3ec98b8    stack   
1115  eb215c03-95a0-4058-9ec9-5b603603d97e   random   
1116  f23c667d-3a0b-4130-9ff2-d84ddd8a00d7    stack   
1117  571e02b1-664d-479b-8579-0159b5a6f526    stack   

                                            preferences  category allocation  \
916   [9, 6, 12, 7, 10, 4, 2, 1, 13, 8, 5, 14, 3, 0,...         1       None   
917   [0, 4, 8, 9, 2, 7, 12, 5, 11, 3, 1, 6, 10, 13,...         1       None   
918   [0, 4, 8, 9, 2, 7, 12, 5, 11, 3, 1, 6, 10, 13,...         1       None   
919   [10, 6, 8, 9, 3, 12, 14, 2, 7, 5, 1, 11, 4, 0,...         1       None   
920   [0, 4, 8, 9, 2, 7, 12, 5, 11, 3, 1, 6, 10, 13,...         1       None   
...                                                 ...       ...        ...   
1113  [0, 4, 8, 9, 2, 7, 12, 5, 11, 3, 1, 6, 10, 13,...         1       None   
1114  [0, 4, 8, 9, 2, 7, 12, 5, 11, 3, 1, 6, 10, 13,...         1       None   
1115  [7, 14, 13, 5, 8, 1, 9, 4, 10, 6, 3, 2, 12, 0,...         1       None   
1116  [0, 4, 8, 9, 2, 7, 12, 5, 11, 3, 1, 6, 10, 13,...         1       None   
1117  [0, 4, 8, 9, 2, 7, 12, 5, 11, 3, 1, 6, 10, 13,...         1       None   

     preference_number  is_dra  
916               None   False  
917               None   False  
918               None   False  
919               None   False  
920               None   False  
...                ...     ...  
1113              None   False  
1114              None   False  
1115              None   False  
1116              None   False  
1117              None   False  

[202 rows x 7 columns]

In [3]:
import numpy as np
empty_arr = np.empty((0,2), np.int32)
np.vstack([empty_arr, [1,1]])

array([[1, 1]])

In [1]:
import cupy as cp
empty_arr = cp.empty((0,2), cp.int32)
combined_arr = cp.vstack([empty_arr, [1,1]])
cp.sum(combined_arr)

array(2)

In [2]:
constant = 500
cp.asarray(constant)

array(500)